### ISSUE TITLE
How can we choose the format of the date?

### ISSUE THREAD

**Issue by epceylon** [misha130/ion-datepicker#44]
Instead of Wed Mar 25 2015 08:00:00 GMT+0800 (+08) format we would like to use a format like DD/MM/YYYY. Is this possible?

**Comment by misha130** [comment]
It returns a date object so you can format it as ever you like.

returnValue | date:'DD/MM/YYYY'


On Sep 10, 2017 12:57, "epceylon" <notifications@github.com> wrote:

Instead of Wed Mar 25 2015 08:00:00 GMT+0800 (+08) format we would like to
use a format like DD/MM/YYYY. Is this possible?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/misha130/ion-datepicker/issues/44>, or mute the thread

**Comment by smadurange** [comment]
Thanks. You can close this.
