### ISSUE TITLE
Month with first day = sunday and week starts from monday -> disappearing days...

### ISSUE THREAD

**Issue by jcoppieters** [misha130/ion-datepicker#47]
Hello,

In october 2017 the first day is a sunday, if you have a datepicker with "doesStartFromMonday === true" then the first day is not shown. (see screenshot)

I've fixed it by adding 1 line DatePicker.service ->
DateService.createDateList(currentDate) {
        var firstDayOfWeek = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1).getDay();
        if (this.doesStartFromMonday() && firstDayOfWeek === 0) firstDayOfWeek = 7;
        ...
}

It would be nice if you could fix this in the npm archive, otherwise we'll have to copy the datepicker files into our source tree.

many thanks,
Johan.

![screen shot 2017-09-19 at 12 04 18](https://user-images.githubusercontent.com/4351748/30591341-a8349498-9d42-11e7-8d0a-c9f19c77c534.JPG)

**Comment by misha130** [comment]
Could you post your configuration? Like just the html?

Also what is the name of your package and version?

I tried to reproduce this bug and I couldn't do it. I've set the locale to en-US which has starts from monday and even tried to add custom localestrings.

![](https://i.gyazo.com/42061e9f4c2368057c71e09301c599ce.png)
![](https://i.gyazo.com/00ee524ee8ba23c4252dff8b5ef1fa91.png)

**Comment by jcoppieters** [comment]
Misha,

in my template ( "_" pipe is our translation pipe):
```
    <ion-item ion-datepicker (ionChanged)="dpStartChange($event)"
          [value]="shift.at"
          [min]="dpStart.min"
          [max]="dpStart.max" [modalOptions]="{showBackdrop: true}"
          [localeStrings] = "ctrl.datePickerLocale()">
      <ion-label>{{"CreateJob.startDate" | _ }}</ion-label>
      <ion-note item-content item-end ion-text color="manatee">{{shift.at | df: "Dx, d Mx yy"}}</ion-note>
    </ion-item>
```

in my base controller (the translate method translates to the correct language of the app, we need Dutch, French, ... with sometimes atypical translations):
```
  datePickerLocale() {
    const loc = { monday: true, 
        weekdays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'], 
        months: ['january', 'february', 'march', 'april', 'may', 'june', 
                 'july', 'august', 'september', 'october', 'november', 'december'] 
    };
    loc.weekdays = loc.weekdays.map(wd => this.translate(wd));
    loc.months = loc.months.map(mn => this.translate(mn));
    return loc;
  }
```

version:
$ npm view ionic3-datepicker
 
```
{ name: 'ionic3-datepicker',
  description: 'A date picker for ionic 3 and 2 framework',
  'dist-tags': { latest: '2.5.1' },
  versions: [ '2.4.8', '2.4.9', '2.4.10', '2.4.11', '2.4.12', '2.5.0', '2.5.1' ],
  maintainers: [ 'pauloedsr <pauloedsr@gmail.com>' ],
  time: 
   { modified: '2017-09-01T13:26:18.222Z',
     created: '2017-07-20T12:16:20.165Z',
     '2.4.8': '2017-07-20T12:16:20.165Z',
     '2.4.9': '2017-07-20T12:22:17.193Z',
     '2.4.10': '2017-07-20T12:53:55.564Z',
     '2.4.11': '2017-07-20T12:59:56.657Z',
     '2.4.12': '2017-07-20T13:10:47.459Z',
     '2.5.0': '2017-09-01T12:28:07.372Z',
     '2.5.1': '2017-09-01T13:26:18.222Z' },
  homepage: 'https://github.com/pauloedsr/ionic3-datepicker#readme',
  keywords: 
   [ 'ionic3-datepicker',
     'ionic3',
     'ionic3 datepicker',
     'datepicker',
     'datepicker ionic3',
     'datepicker for ionic3',
     'datepicker for ionic3 framework' ],
  repository: 
   { type: 'git',
     url: 'git+https://github.com/pauloedsr/ionic3-datepicker.git' },
  author: 'Paulo Eduardo <pauloedsr@gmail.com>',
  bugs: { url: 'https://github.com/pauloedsr/ionic3-datepicker/issues' },
  license: 'MIT',
  readmeFilename: '',
  version: '2.5.1',
  main: 'index.js',
  scripts: 
   { ngc: 'ngc',
     build: 'npm run ngc && node ./scripts/copy-package',
     publishPackage: 'npm run build && cd dist && npm publish',
     dev: 'tsc --watch' },
  dependencies: {},
  dist: 
   { integrity: 'sha512-fRhd3gDCo2FTGcpdarAtCxzm4g1QsA+qAFQL3ng37V/cMJwtaGZIlu+4wx9LquzE2EQyrtDZimbGDm22LPnKPw==',
     shasum: 'd1c28c09386e1901726ccdad92602a7db991cf10',
     tarball: 'https://registry.npmjs.org/ionic3-datepicker/-/ionic3-datepicker-2.5.1.tgz' },
  directories: {} }
```

**Comment by misha130** [comment]
ionic3-datepicker is a fork of my datepicker which is an old version plus I
guess new things?

Try ion-datepicker instead

On Sep 20, 2017 12:01, "Johan Coppieters" <notifications@github.com> wrote:

Misha,

in my template ( "_" pipe is our translation pipe):

    <ion-item ion-datepicker (ionChanged)="dpStartChange($event)"
          [value]="shift.at"
          [min]="dpStart.min"
          [max]="dpStart.max" [modalOptions]="{showBackdrop: true}"
          [localeStrings] = "ctrl.datePickerLocale()">
      <ion-label>{{"CreateJob.startDate" | _ }}</ion-label>
      <ion-note item-content item-end ion-text
color="manatee">{{shift.at | df: "Dx, d Mx yy"}}</ion-note>
    </ion-item>

in my base controller (the translate method translates to the correct
language of the app, we need Dutch, French, ... with sometimes atypical
translations):

  datePickerLocale() {
    const loc = { monday: true,
        weekdays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
        months: ['january', 'february', 'march', 'april', 'may', 'june',
                 'july', 'august', 'september', 'october', 'november',
'december']
    };
    loc.weekdays = loc.weekdays.map(wd => this.translate(wd));
    loc.months = loc.months.map(mn => this.translate(mn));
    return loc;
  }

version:
$ npm view ionic3-datepicker

{ name: 'ionic3-datepicker',
  description: 'A date picker for ionic 3 and 2 framework',
  'dist-tags': { latest: '2.5.1' },
  versions: [ '2.4.8', '2.4.9', '2.4.10', '2.4.11', '2.4.12', '2.5.0',
'2.5.1' ],
  maintainers: [ 'pauloedsr <pauloedsr@gmail.com>' ],
  time:
   { modified: '2017-09-01T13:26:18.222Z',
     created: '2017-07-20T12:16:20.165Z',
     '2.4.8': '2017-07-20T12:16:20.165Z',
     '2.4.9': '2017-07-20T12:22:17.193Z',
     '2.4.10': '2017-07-20T12:53:55.564Z',
     '2.4.11': '2017-07-20T12:59:56.657Z',
     '2.4.12': '2017-07-20T13:10:47.459Z',
     '2.5.0': '2017-09-01T12:28:07.372Z',
     '2.5.1': '2017-09-01T13:26:18.222Z' },
  homepage: 'https://github.com/pauloedsr/ionic3-datepicker#readme',
  keywords:
   [ 'ionic3-datepicker',
     'ionic3',
     'ionic3 datepicker',
     'datepicker',
     'datepicker ionic3',
     'datepicker for ionic3',
     'datepicker for ionic3 framework' ],
  repository:
   { type: 'git',
     url: 'git+https://github.com/pauloedsr/ionic3-datepicker.git' },
  author: 'Paulo Eduardo <pauloedsr@gmail.com>',
  bugs: { url: 'https://github.com/pauloedsr/ionic3-datepicker/issues' },
  license: 'MIT',
  readmeFilename: '',
  version: '2.5.1',
  main: 'index.js',
  scripts:
   { ngc: 'ngc',
     build: 'npm run ngc && node ./scripts/copy-package',
     publishPackage: 'npm run build && cd dist && npm publish',
     dev: 'tsc --watch' },
  dependencies: {},
  dist:
   { integrity:
'sha512-fRhd3gDCo2FTGcpdarAtCxzm4g1QsA+qAFQL3ng37V/cMJwtaGZIlu+4wx9LquzE2EQyrtDZimbGDm22LPnKPw==',
     shasum: 'd1c28c09386e1901726ccdad92602a7db991cf10',
     tarball: 'https://registry.npmjs.org/ionic3-datepicker/-/ionic3-datepicker-2.5.1.tgz'
},
  directories: {} }

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/misha130/ion-datepicker/issues/47#issuecomment-330790917>,
or mute the thread

**Comment by jcoppieters** [comment]
OK, sorry Misha, 

don't know why the ionic3-datepicker has gotten into the package.json.

I will try to get it out in the next hour and report back.
I suppose you support the same options.

Johan.

**Comment by jcoppieters** [comment]
Works like a charm.... sorry for the extra work...  Why do people fork ifthe only thing they do is leave bugs in it... (I looked at your DateService and it already has my suggestion).

Nice work.
