### ISSUE TITLE
Hard coded platform style?

### ISSUE THREAD

**Issue by rfoel** [misha130/ion-datepicker#48]
Why does the component has these hard coded style? Example:

`
<button (tap)="onDone($event)" ion-button=""  class="button button-clear button-small disable-hover button button-ios button-default button-default-ios">
      <span class="button-inner">{{config.okText || 'OK'}}</span><div class="button-effect"></div>
</button>
`

**Comment by misha130** [comment]
Legit answer: I did not know how to make it just ion-button.
It wouldn't add the styles dynamicly when I tested it so I just copy pasted
the styles I had.

If I probably try nowdays and remove all of them it would work fine.

On Sep 23, 2017 5:21 PM, "Rafael Franco" <notifications@github.com> wrote:

Why does the component has these hard coded style? Example:

<button (tap)="onDone($event)" ion-button="" class="button button-clear
button-small disable-hover button button-ios button-default
button-default-ios"> <span class="button-inner">{{config.okText ||
'OK'}}</span><div class="button-effect"></div> </button>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/misha130/ion-datepicker/issues/48>, or mute the thread

**Comment by rfoel** [comment]
Fair enough. I've done some testing and it doesn't quite work with just `ion-button`. Not sure why though.

**Comment by misha130** [comment]
Closed in 2.7.2 5 months later.
