### ISSUE TITLE
temp date is sometimes an invalid date when changing month

### ISSUE THREAD

**Issue by uptownjimmy** [misha130/ion-datepicker#98]
In our app, the max date is +30 days from today's date. 

When we open the modal today (May 7th) and click to the next month, an invalid date (June 7th) is highlighted with the _datepicker-temp_ class:

`class="col calendar-cell datepicker-date-col datepicker-disabled datepicker-temp"`

We have logic to prevent an invalid date from being saved to our API, but it seems like bad UI for the datepicker to default the temp date selector to an invalid date.

**Comment by misha130** [comment]
Just to check, the date that is selected next time is 6th or 8th of the
month?

**Comment by uptownjimmy** [comment]
When I click the next month arrow to June, the date is the same as it was in May when I opened the datepicker: the 7th. But that's +31 days, and our cutoff is +30. When I then click another _valid_ date, like the 6th, the 7th is greyed out and not clickable, as expected. 

But it definitely starts out as "datepicker-temp". I can post screenshots if you need.

**Comment by misha130** [comment]
I think I understand, will try to fix

**Comment by uptownjimmy** [comment]
I believe the problem is in datepicker.component.ts, on line 759. The conditional there is not met, currently, because _maxTestDate.getMonth()_ = 6 (or July) and _testDate.getMonth()_ = 5 (or June). So the line of code at 228 never executes, and _testDate_ is never set to _this.config.max_.

When I comment out lines 226 and 230, the app seems to work properly, but I'm not sure yet if I have broken something else by doing that.

**Comment by Paul-Etienne** [comment]
I've just created a PR addressing this issue.

There were cases where maxTestDate would be set to the first day of the next month, as @uptownjimmy stated. This was simply because `maxTestDate.setDate(0);` was done before `maxTestDate.setMonth(maxTestDate.getMonth() + 1);`.

The max date was set to the last day of the previous month and only then a full month was added. It looks like there were problems when the corresponding month had less days than the previous one. It would end up in the date being set to the first day of the next month.

By setting the date a month later and then to the last day of the previous month with `maxTestDate.setDate(0);`, maxTestDate correctly sets to the last day of the current month.

**Comment by misha130** [comment]
Fixed in the above PR.
Updated npm to version 2.8.1

**Comment by Paul-Etienne** [comment]
I've just created another PR after realizing a problem was remaining in some limit cases where the `maxTestDate` would be set to the last day of the next month. This issue should be permanently addressed with this new fix.
I apologize for the quack.
